// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace DungeonMap.Constants
{

public enum RoomState : sbyte
{
  InFog = 0,
  Visible = 1,
  Visited = 2,
  HeroThere = 3,
};


}
